### ISSUE TITLE
GUI problem 

### ISSUE THREAD

**Issue by mohamedmarzouk22** [tubiana/ttclustGUI#4]
While I am trying to compile the GUI on macOS Big Sur I get this error 
ERROR: Command errored out with exit status 1: /Users/macbook/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/09/f9r3v2011y37jr6_27kt2g_r0000gn/T/pip-install-c49tasn6/wxpython_d710fed472f141f9b9b70255f9d8d828/setup.py'"'"'; __file__='"'"'/private/var/folders/09/f9r3v2011y37jr6_27kt2g_r0000gn/T/pip-install-c49tasn6/wxpython_d710fed472f141f9b9b70255f9d8d828/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/09/f9r3v2011y37jr6_27kt2g_r0000gn/T/pip-record-5e_3s22n/install-record.txt --single-version-externally-managed --compile --install-headers /Users/macbook/anaconda3/include/python3.7m/wxpython Check the logs for full command output.

**Comment by tubiana** [comment]
Dear Mohamed, 

Thank you for your interest in TTClust. Unfortunately I have some issues maintaining this GUI compatibility. 
I am working on a new GUI that could integrate other types of analysis but it's not published and totally ready yet. 
In the meantime, I strongly advise you to use the command line version only https://github.com/tubiana/TTClust.
It is also available on PIP (`pip install ttclust`) and Conda (`conda install -c tubiana ttclust`) and this version is up to date :-) 

Best regards,
Thibault.

**Comment by mohamedmarzouk22** [comment]
thank you for declaring. I just installed the command line version. 
Waiting for your new edition of GUI soon.
